
stages:
  data_ingestion:
    cmd: python3 src/classifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/classifier/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/chicken_images

  
  
  prepare_base_model:
    cmd: python3 src/classifier/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/classifier/pipeline/stage_02_prepare_base_model.py
      - config/config.yaml
    parameters:
      prepare_base_model.IMAGE_SIZE:
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model




  training:
    cmd: python3 src/classifier/pipeline/stage_03_training.py
    deps:
      - src/classifier/pipeline/stage_03_training.py
      - src/classifier/componets/prepare_callbacks.py
      - config/config.yaml
      - artifacts/data_ingestion/chicken_images
      - artifacts/prepare_base_model
    parameters:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      -artifacts/training/model.keras



  evaluation:
    cmd: python3 src/classifier/pipeline/stage_04_evaluation.py
    deps:
      - src/classifier/pipeline/stage_04_evaluation.py
      - config/config.yaml
      - artifacts/data_ingestion/chicken_images
      - artifacts/training/model.keras
    parameters:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
      - scores.json:
          cache: false
      




  

    
      
    



  



